# Generated by Django 4.0.6 on 2022-08-02 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('Department_head',)},
        ),
        migrations.AlterUniqueTogether(
            name='doctor',
            unique_together={('Contact_number',)},
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('contact_number',)},
        ),
    ]
